[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
fitparser = "0.10.0"
datafusion = "43.0"
tokio = { workspace = true }
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
insta = "1.46.0"
